version: 0.2

phases:
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
artifacts:
  files:
    - build/**/*